(()=>{
"use strict";
document.addEventListener("contextmenu",event=>event.preventDefault());
const C=2*Math.PI*48,themes=["dark-cyan","neon-purple","machine","hud-green"],upHistory=[],downHistory=[];
let chart=null,refreshTimer=null,lastValues={};
function byId(id){return document.getElementById(id)}
function setText(id,value){if(lastValues[id]===value)return;const element=byId(id);if(element)element.textContent=value;lastValues[id]=value}
function safeGet(key){try{return localStorage.getItem(key)}catch(error){return null}}
function safeSet(key,value){try{localStorage.setItem(key,value)}catch(error){}}
function getThemeColors(){const style=getComputedStyle(document.body);return{cpu:style.getPropertyValue("--accent-cpu").trim(),gpu:style.getPropertyValue("--accent-gpu").trim(),mem:style.getPropertyValue("--accent-mem").trim(),net:style.getPropertyValue("--accent-net").trim()}}
function normalizeHex(color){if(typeof color!=="string")return null;const value=color.trim(),hex=value.startsWith("#")?value.slice(1):"";if(/^[0-9a-fA-F]{3}$/.test(hex))return hex.split("").map(char=>char+char).join("");if(/^[0-9a-fA-F]{6}$/.test(hex))return hex;return null}
function mixHex(first,second,t,fallback=first){const a=normalizeHex(first),b=normalizeHex(second),safe=normalizeHex(fallback);if(!a||!b)return safe?"#"+safe:"#484f58";const ratio=Math.max(0,Math.min(1,Number(t)||0)),rgb=[0,2,4].map(index=>Math.round(parseInt(a.slice(index,index+2),16)+(parseInt(b.slice(index,index+2),16)-parseInt(a.slice(index,index+2),16))*ratio));return "rgb("+rgb.join(", ")+")"}
function loadColor(value,base){if(value<50)return mixHex(base,"#d29922",value/50,base);if(value<90)return mixHex("#d29922","#f85149",(value-50)/40,base);return "#f85149"}
function refreshChartColors(){if(!chart)return;const colors=getThemeColors();chart.setOption({series:[{lineStyle:{color:colors.net},areaStyle:{color:colors.net,opacity:.14}},{lineStyle:{color:colors.gpu},areaStyle:{color:colors.gpu,opacity:.14}}]},false)}
function applyTheme(index){const next=(index+themes.length)%themes.length;document.documentElement.dataset.theme=themes[next];safeSet("themeIdx",String(next));refreshChartColors();const button=byId("themeBtn");if(button)button.title="切换主题: "+themes[next];refresh()}
function initTheme(){const saved=Number(safeGet("themeIdx"));applyTheme(Number.isInteger(saved)?saved:0)}
function updateClock(){const now=new Date();setText("clock",now.getFullYear()+"年"+(now.getMonth()+1)+"月"+now.getDate()+"日 "+String(now.getHours()).padStart(2,"0")+":"+String(now.getMinutes()).padStart(2,"0")+":"+String(now.getSeconds()).padStart(2,"0"))}
function renderRing(ring,value,percent,base){if(!ring||!value)return;const raw=Number(percent);if(!Number.isFinite(raw)||raw<0){ring.style.stroke="#484f58";ring.style.strokeDashoffset=String(C);setText(value.id,"N/A");return}const amount=Math.max(0,Math.min(100,raw)),color=loadColor(amount,base);ring.style.stroke=color;ring.style.strokeDashoffset=String(C*(1-amount/100));value.style.color=color;if(lastValues[value.id]!==amount){value.textContent=Math.round(amount)+"%";lastValues[value.id]=amount}}
function initChart(){const element=byId("netChart");if(!element||!window.echarts||chart)return;const colors=getThemeColors();chart=echarts.init(element);chart.setOption({animation:false,grid:{left:0,right:0,top:4,bottom:0},xAxis:{type:"category",show:false,boundaryGap:false},yAxis:{type:"value",show:false,min:0},tooltip:{show:false},series:[{type:"line",data:upHistory,smooth:true,showSymbol:false,lineStyle:{color:colors.net,width:2},areaStyle:{color:colors.net,opacity:.14}},{type:"line",data:downHistory,smooth:true,showSymbol:false,lineStyle:{color:colors.gpu,width:2},areaStyle:{color:colors.gpu,opacity:.14}}]},false)}
function updateChart(up,down){upHistory.push(up);downHistory.push(down);if(upHistory.length>60)upHistory.shift();if(downHistory.length>60)downHistory.shift();if(chart)chart.setOption({series:[{data:upHistory},{data:downHistory}]},false)}
async function resetTraffic(){if(!confirm("确认清零历史用量？"))return;try{const response=await fetch("/api/reset",{method:"POST"});if(!response.ok)throw Error(response.status)}catch(error){alert("清零失败")}}
async function refresh(){try{const response=await fetch("/api/stats",{cache:"no-store"});if(!response.ok)throw Error(response.status);const data=await response.json(),colors=getThemeColors();renderRing(byId("cpuProgress"),byId("cpuValue"),data?.cpu?.total,colors.cpu);renderRing(byId("gpuProgress"),byId("gpuValue"),data?.gpu?.available===true?data?.gpu?.total:-1,colors.gpu);renderRing(byId("memoryProgress"),byId("memoryValue"),data?.memory?.percent,colors.mem);setText("cpuModel",data?.cpu?.model??"未知 CPU");setText("gpuModel",data?.gpu?.model??"未知显卡");setText("memoryDetail",Number(data?.memory?.usedGB??0).toFixed(1)+" / "+Number(data?.memory?.totalGB??0).toFixed(1)+" GB");setText("netUp",Number(data?.net?.upMbps??0).toFixed(2)+" mbps");setText("netDown",Number(data?.net?.downMbps??0).toFixed(2)+" mbps");setText("netHistory",Number(data?.net?.totalGB??0).toFixed(2)+" GB");updateChart(Number(data?.net?.upMbps??0),Number(data?.net?.downMbps??0));const error=byId("errorMessage");if(error)error.style.display="none"}catch(error){const box=byId("errorMessage");if(box)box.style.display="flex"}}
function fitStage(){const stage=byId("stage"),hint=byId("rotateHint"),width=window.innerWidth,height=window.innerHeight;if(!stage)return;if(hint)hint.style.display=height>width?"flex":"none";const scale=Math.min(width/1920,height/1080);stage.style.transform="translate(-50%, -50%) scale("+scale+")"}
function toggleFullscreen(){try{if(document.fullscreenElement)document.exitFullscreen();else if(document.documentElement.requestFullscreen)document.documentElement.requestFullscreen().catch(()=>{})}catch(error){}}
async function rotatePage(){try{if(!document.fullscreenElement&&document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();if(screen.orientation?.lock)await screen.orientation.lock("landscape")}catch(error){}}
function start(){fitStage();initTheme();initChart();refreshChartColors();byId("themeBtn")?.addEventListener("click",()=>applyTheme((Number(safeGet("themeIdx"))||0)+1));byId("resetBtn")?.addEventListener("click",resetTraffic);byId("fullscreenBtn")?.addEventListener("click",toggleFullscreen);byId("rotateBtn")?.addEventListener("click",rotatePage);byId("hintFullscreenBtn")?.addEventListener("click",event=>{event.stopPropagation();toggleFullscreen()});byId("hintRotateBtn")?.addEventListener("click",event=>{event.stopPropagation();rotatePage()});updateClock();refresh();refreshTimer=setInterval(()=>{updateClock();refresh()},1000);window.addEventListener("resize",fitStage,{passive:true});window.addEventListener("orientationchange",fitStage,{passive:true})}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",start,{once:true});else start();
})();
